---
title: Thoughts on Remote Teaching from Spring & Summer 2020
author: Benjamin Capistrant
date: '2020-08-22'
categories: []
tags:
  - Learning Theory
  - Instructional Design
  - Teaching
subtitle: ''
summary: 'Reflections on sudden and more planned remote teaching in 2020.'
authors: []
lastmod: '2020-08-22T16:27:44-04:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

Over the past few years, I have taught in the Program on Statistical & Data Sciences (SDS) for undergraduate students and in the MSW and PhD programs at the School for Social Work (SSW). Typically, this means I'm teaching January - May in SDS and then June - August in SSW.

What this meant in 2020, is that I both:

- shifted to remote teaching quickly mid-semester in Spring and also 
- taught two 5-week terms that were entirely remote from beginning to end during the Summer.

These students are really different, I teach different material in each program, with different sized classes such that there's a different teaching style, and a wildly different pace (14 weeks vs. 5 weeks). Which is to say, on some level, any comparison between the two teaching experiences is absurd.

That said, it has been interesting to reflect on what worked for classes that were entirely remote and a cumulative reflection back on the previous 5 or so months (has it not been 5 years?) of emergency remote teaching. Some of it is stuff that is pretty general or not particularly surprising but bears explicit mention, and other pieces of it are more specific.  

Essentially, it boils down to: 
1. be flexible and human you have wherewithal to be; 
2. setting up synchronous learning takes (more) work and pre-planning; and 
3. use asynchronous learning approaches that meaningfully build community and interactivity.


# Common sense stuff (\*)

- __Students need scheduling flexibility.__ When I first started teaching at Smith, I modeled my syllabus on others I had seen (including late assignment policy) and felt like the fairest thing to do to students was to hold to it very closely. Over time, I have softened on that considerably (and probably still have room to go), and I'm not sure how I could have done this kind teaching without being open to just about every possible iteration of deadlines. Multiple students had deaths in their families, students who were sick, moving, etc. 

- __Less is more.__ Cutting the number of assignments was critical to giving all students flexibility and autonomy, and to allow everyone the time to focus on material. When we went remote in spring, I cut a test, a cumulative group project, and some homework assignments. This summer, a student approached me to say they felt like 4 assignments -- again, based on someone else's syllabus -- was going to be a ton of work, and asked if there could be fewer. Sure! Another class got much less far along into the project we had planned -- that's fine! They did great work and had many opportunities for learning.

- __Making space for something other than reading/writing papers and videos on Zoom.__ I revised a final project format to have many more options -- a podcast / interview, an infographic, blog posts, etc. -- in part to change things up from static paper writing or a Zoom-based final-class presentation that meant that much more time on Zoom.

- __It's really hard, no one likes it, and it wears on everyone over time.__ Going remote in late March meant there were ~5 weeks left; my summer classes ran in two 5 week terms (some across both terms for 10 total weeks). Those are short windows of time, enough for the light at the end of the tunnel to be apparent at the start. Each class and week was different; just like you can "feel" when it's midterms season on campus, you can feel it on Zoom, too. There were noticeable ebbs and flows, and that's just part of the semester.

\* I'm a (recently) tenured, white identifying, cisgender, queer man teaching at a private college and I know that I benefited from feeling able to make these changes without losing credibility with students, without repercussions from colleagues and administration, including the threat of messing up opportunities to come teach again that contract / adjunct / contingent faculty face. For whatever it's worth, I was in an administrative role as a chair of part of the SSW curriculum this year where I "oversaw" ~15 adjunct faculty and advocated for and supported them to make whatever decisions made sense for them and their students. Even still, not to name the many ways my social position and privilege lent to being able to take these "common sense" steps would be naive at best.

# Zoom mechanics & synchronous learning

I essentially kept my Spring classes synchronous with recorded class sessions so that people who couldn't attend could still access the material. For summer classes, we would typically have had 4 hour of class per week (for ~2 credits / 5 week term), which I cut to 1.5 hours and supplemented with (limited) asynchronous activities. Some thoughts about how Zoom has been working across those different classes.

- __Don't require cameras to be on.__ I encouraged people on Day 1 to turn their cameras off whenever they needed to, no justification needed. Zoom is really intimate in many ways, and many don't want to invite everyone in the class into their home. Many students have anxiety, attention issues, body dysmorphia, etc., in ways that having their camera on is counterproductive to learning. Sometimes you're really not in a place to be sitting up and you're actually more able to participate if you're lying down and just listening. Maybe there are (grand)kids / siblings coming in and out. Often having videos on takes a lot of data / wifi bandwidth that someone may not have. And frankly, sometimes someone falls asleep in class when you're in a building on campus, and you probably just let them sleep. In moments when I had weird camera issues, students thought I was modeling the behavior and really appreciated it (I just needed to reboot to connect to my webcam...). And in a week when I wasn't feeling well, I needed to be able to use the policy myself. [Others have noted similar phenomena :).](https://twitter.com/roopikarisam/status/1296989959019257856?s=20)

One note that bears particular mention: having your camera off may be particularly important for students of minoritized identities at predominantly white institutions. To my mind, the protection of not having to hide your disdain on your face or to be able to retreat after a microaggression is one of the ways I could try to minimize the toll and additional emotional labor students of the global majority are expected to do at primarily white institutions like mine.

- __Start each class with an activity.__ I used Poll Everywhere so predictably at the beginning of class that it became a joke. Starting off with a word cloud or a prompt to get responses (you could do this in the Chat or with closed ended polls in Zoom, too) was a great way to get people "talking" and to have something for us all to respond to. In some instances, I would do this in Google Docs; set up a document with the prompts and placeholders for as many people in the class to respond (like numbered lines for 1-30 for each of the 30 student, so they aren't all typing over each other), and paste the link to the document into the chat. I would usually have done this in person, and that would have required a little less advanced planning.

- __Set up opportunities to talk in full class discussions.__ When we went remote mid-semester, I already had rapport with students, they had practice asking questions in class, and knew each other at least by being in the same room with one another before. Those dynamics carried over into Zoom more or less -- some used the chat more, but people seemed very interactive. It was harder to build the rapport or environment that would make people feel comfortable to jumping into a class discussion in a gallery view of 22 students. It took work, planning, and trial/error.

I likened taking yourself off mute in that kind of class as putting your hand up in a 130 person lecture hall to ask a question -- it feels like a big step! At a minimum, you literally have to lean forward, click unmute, say what you have to say, and then unmute yourself. There's nothing very natural about it. Structuring small group discussions that came back to large group discussions were key. I found I had to rely on a more organized think-pair-share sort of model.

Here's the catch: _breakout rooms feel like the exact opposite -- they're extremely intimate_. Even if they are also [super awkward](https://www.reddit.com/r/umass/comments/ih25d9/i_hate_virtual_learning/g2xhd6j/?context=3_), they're awkward in a small group that is very private. So it is useful to ask the group to assign who from the group will report back. Otherwise, it can feel like you're betraying trust of who said what in the breakout group. In a classroom, you self-censor more because you know that you can be overheard and that you've overhearing what others are talking about. Breakout rooms create really small spaces, which can be great, but perhaps too small. It's also more awkward to join a group to check in and see what they're talking about -- it's like you just appear out of thin air in the middle of their desks in a classroom like a genie and without notice. So tread lightly with breakout groups.

- __Google Docs are your friend.__ Sharing documents and slides for people to view and/or edit directly is extremely useful to know that people are looking at the same information.

- __Use synchronous time for group work.__ Even in the summer teaching where everyone was in the U.S. and across only 3 time zones, group work was really challenging, logistically and [otherwise.](https://www.buzzfeed.com/chuphanginichandrakanthan/group-assignments) With people all over the globe in the Spring, it was totally impractical. I shortened projects, made collaboration optional and with a clear rubric for what a project that two people worked on would entail vs. one person.

# Asynchronous learning

Many classes over the summer opted to do shorter amounts of synchronous time and augment with asynchronous activities to give a break from Zoom and allow for flexibility. The role of the asynchronous work wasn't always clear to students -- it just seemed like more work! -- in part because the synchronous work plus the readings and assignments seemed like plenty.  Many of the classes in my sequence found that the asynchronous activities did not work as well as planned. Discussion forums fell flat and felt like busy work, watching extra video content and writing responses still felt very taxing, etc. My hunch is that the sense of isolation was a piece of what wasn't working. I found a few approaches worked to address this.

- __VoiceThread__ [VoiceThread](https://voicethread.com/) was a great way to make that video (or other content) a bit more interactive. You can upload/link YouTube or other web content and students are able to comment right at the point in the video that they have a question, comment, etc. Everyone could see each others' comments, reply to them, etc. You could even embed or prompt questions yourself for a discussion at one point. There are ways to connect this with your LMS if your institution has it set up to automatically record participation, etc., but I didn't bother with that.  This seemed really successful and felt like it facilitated more peer-to-peer learning and engagement in the context of the thing they were asked to comment on vs. a discussion forum post. I believe it's free

- __Perusall__ Similar to VoiceThread but better for text content like readings, [Perusall](https://perusall.com/) was a great mechanism to crowd-source reading assignments. Students could highlight, make comments / questions on specific passages, and discuss or respond to others comments (including mine). It's free to use and has similar LMS integration that I wasn't able to muster.

- __Slack__ In Spring, I had already actively been using Slack and it continued to work well for course communication, polls, etc. In order to minimize the technology that we were asking of students, I opted not to use Slack over the summer. I think it could have built a little more of a community with real time interactions, but it would really require having at least 2 classes actively using Slack otherwise it's just an annoying complication of your class.

- __Don't overprep materials__ I have a hard time finding the balance here. I spend a lot of time building interactive tutorials in `R` that got used pretty minimally; I bet I spend 3x as much time to build them as they were used. And I had a hunch about that going in and knew it was a longer term investment. But still, I tend to overprep (while simultaneously underprepping?) and had high hopes for [really dynamic](https://www.youtube.com/watch?v=D7vooDcxUaA) [video content](https://www.youtube.com/watch?v=s0lQJvBC_1I) and perfecting the best way to do X thing remotely, but I ultimately just couldn't get to it. And I cut myself slack on that.

# In Sum
There will be many more lessons to learn throughout Fall 2020 and Spring 2021 semesters about what our students need to learn in this arrangement. It's an evolving thing that we're all being asked to do. There are [great](https://www.amazon.com/Small-Teaching-Online-Applying-Learning/dp/1119619092) [resources](https://acue.org/programs/faculty/) about teaching online that I found really useful, even though many of them talk about teaching "online" in a fundamentally different non-pandemic world. Being the best, most flexible human you can within your institution; with intention around synchronous learning; and inventive, if sparing, use of asyncronous leanhing that facilitates connection will go a long way.
